name       : python-resolvelib
version    : 0.8.1
release    : 1
source     :
    - https://github.com/sarugaku/resolvelib/archive/refs/tags/0.8.1.tar.gz : f400ebd5e60361b3b328241f4aded5a0f7665e46a83c374fea86d874cff0ffd5
license    : ISC
component  : programming.python
summary    : Resolve abstract dependencies into concrete ones
description: |
    ResolveLib at the highest level provides a Resolver class that includes dependency resolution logic.
    You give it some things, and a little information on how it should interact with them, and it will spit out a resolution result.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install

